import test from'node:test';import assert from'node:assert/strict';import{writeFile,mkdir}from'node:fs/promises';import{parsePly}from'../src/parse.ts';import{interpolateHoles}from'../src/interpolate.ts';
const ab=(s:string)=>new TextEncoder().encode(s).buffer;
const ascii='ply\nformat ascii 1.0\nelement vertex 3\nproperty float x\nproperty float y\nproperty float z\nproperty uchar red\nproperty uchar green\nproperty uchar blue\nelement face 1\nproperty list uchar int vertex_indices\nend_header\n0 0 0 255 0 0\n2 0 0 0 255 0\n0 2 0 0 0 255\n3 0 1 2\n';
function binary(le:boolean){const h=ab(`ply\nformat binary_${le?'little':'big'}_endian 1.0\nelement vertex 3\nproperty float x\nproperty float y\nproperty float z\nproperty uchar red\nproperty uchar green\nproperty uchar blue\nelement face 1\nproperty list uchar int vertex_indices\nend_header\n`),b=new ArrayBuffer(h.byteLength+58);new Uint8Array(b).set(new Uint8Array(h));const v=new DataView(b);let o=h.byteLength;for(const[i,p]of[[0,0,0],[2,0,0],[0,2,0]].entries()){for(const x of p){v.setFloat32(o,x,le);o+=4;}for(let c=0;c<3;c++)v.setUint8(o++,c===i?255:0);}v.setUint8(o++,3);for(let i=0;i<3;i++){v.setInt32(o,i,le);o+=4;}return b;}
test('ASCII RGB mesh',()=>{const g=parsePly(ab(ascii));assert.equal(g.count,3);assert.equal(g.triangles,1);assert.deepEqual(g.center,[1,1,0]);assert.deepEqual(Array.from(g.indices!),[0,1,2]);assert.equal(g.colors![0],1);});
for(const le of[true,false])test(`Binary ${le?'LE':'BE'}`,()=>{const g=parsePly(binary(le));assert.deepEqual(Array.from(g.positions),[-1,-1,0,1,-1,0,-1,1,0]);assert.equal(g.colors![4],1);assert.deepEqual(Array.from(g.indices!),[0,1,2]);});
test('CRLF',()=>assert.equal(parsePly(ab(ascii.replaceAll('\n','\r\n'))).count,3));
test('Malformed/truncated/oversized file rejects',()=>{assert.throws(()=>parsePly(ab('not a ply')));assert.throws(()=>parsePly(binary(true).slice(0,-10)));assert.throws(()=>parsePly(ab(ascii.replace('vertex 3','vertex 8000001'))));});
test('Interpolation preserves samples, fills internal gap, leaves exterior empty',()=>{const p=new Uint8ClampedArray(5*3*4);for(const x of[1,3])p.set([200,100,50,255],(5+x)*4);const q=interpolateHoles(p,5,3,2);assert.deepEqual(Array.from(q.slice(28,32)),[200,100,50,255]);assert.equal(q[3],0);assert.deepEqual(Array.from(q.slice(24,28)),[200,100,50,255]);assert.equal(p[31],0);});
test('Interpolation rejects strong colour discontinuity and invalid radius',()=>{const p=new Uint8ClampedArray([255,0,0,255,0,0,0,0,0,0,255,255]);assert.equal(interpolateHoles(p,3,1,2)[7],0);assert.throws(()=>interpolateHoles(p,3,1,5));});
await mkdir('tests/fixtures',{recursive:true});await writeFile('tests/fixtures/triangle-ascii.ply',ascii);await writeFile('tests/fixtures/triangle-le.ply',new Uint8Array(binary(true)));await writeFile('tests/fixtures/triangle-be.ply',new Uint8Array(binary(false)));await writeFile('tests/fixtures/bad.ply','not a ply');
