import{chromium,expect}from'@playwright/test';import assert from'node:assert/strict';import{readFile,mkdir,writeFile}from'node:fs/promises';
const browser=await chromium.launch({headless:true,...(process.env.TEST_CHROME?{executablePath:process.env.TEST_CHROME}:{}),args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1360,height:920},acceptDownloads:true});const errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url());});await mkdir('tests/output',{recursive:true});
try{
 await page.setContent(await readFile('web/index.html','utf8'),{waitUntil:'load'});await page.locator('#capture-top').waitFor({state:'visible'});assert.equal(await page.locator('#error-card').isVisible(),false,await page.locator('#error-message').textContent());await page.screenshot({path:'tests/output/viewer.png'});
 const before=await page.locator('#camera-values').textContent();await page.mouse.move(570,370);await page.mouse.down();await page.mouse.move(680,440,{steps:15});await page.mouse.up();await expect.poll(()=>page.locator('#camera-values').textContent()).not.toBe(before);
 const pose=async()=>{const text=await page.locator('#camera-values').textContent();return text.split('\n').slice(0,2).map(l=>l.match(/-?\d+\.\d+/g).map(Number));};
 const assertRotate=async(label)=>{const [p,t]=await pose();await page.mouse.move(530,360);await page.mouse.down();await page.mouse.move(640,425,{steps:12});await page.mouse.up();await expect.poll(async()=>JSON.stringify((await pose())[0])).not.toBe(JSON.stringify(p));const [q,u]=await pose();assert(Math.hypot(...u.map((v,i)=>v-t[i]))<.006,label+': rotation must keep target fixed');assert(Math.abs(Math.hypot(...p.map((v,i)=>v-t[i]))-Math.hypot(...q.map((v,i)=>v-u[i])))<.006,label+': radius preserved');};
 await page.keyboard.down('d');await assertRotate('D must not override mouse rotation');await page.keyboard.up('d');
 const rotated=await page.locator('#camera-values').textContent();await page.mouse.wheel(0,-320);await expect.poll(()=>page.locator('#camera-values').textContent()).not.toBe(rotated);
 await assertRotate('rotation after wheel');
 const zoomed=await page.locator('#camera-values').textContent();await page.mouse.move(520,380);await page.mouse.down({button:'right'});await page.mouse.move(565,400,{steps:5});await page.mouse.up({button:'right'});await expect.poll(()=>page.locator('#camera-values').textContent()).not.toBe(zoomed);
 await page.click('#pan');await page.mouse.move(550,380);await page.keyboard.press('Escape');await expect(page.locator('#rotate')).toHaveAttribute('aria-pressed','true');await assertRotate('Escape restores rotation');
 await page.click('#pan');await page.click('#demo');await expect(page.locator('#rotate')).toHaveAttribute('aria-pressed','true');await assertRotate('new data restores rotation');
 await page.selectOption('#view-preset','top');await page.selectOption('#resolution','1280');await page.selectOption('#interpolation','2');const exportPose=await page.locator('#camera-values').textContent();await page.click('#capture-top');await page.locator('#image-dialog').waitFor({state:'visible'});await page.locator('#output-image').evaluate(img=>img.decode());const dims=await page.locator('#output-image').evaluate(img=>[img.naturalWidth,img.naturalHeight]);assert.equal(Math.max(...dims),1280);assert.equal(await page.locator('#camera-values').textContent(),exportPose);
 const download=page.waitForEvent('download');await page.click('#save-image');const item=await download;await item.saveAs('tests/output/render.png');const png=await readFile('tests/output/render.png');assert.equal(png.subarray(1,4).toString(),'PNG');assert.equal(png.readUInt32BE(16),dims[0]);assert.equal(png.readUInt32BE(20),dims[1]);await page.screenshot({path:'tests/output/export.png'});await page.click('#close-dialog');
 for(const f of['triangle-ascii.ply','triangle-le.ply','triangle-be.ply']){await page.setInputFiles('#file-input',`tests/fixtures/${f}`);await expect(page.locator('#file-name')).toHaveText(f);assert.equal(await page.locator('#vertex-count').textContent(),'3');assert.equal(await page.locator('#face-count').textContent(),'1');assert.equal(await page.locator('#error-card').isVisible(),false);}
 await page.setInputFiles('#file-input','tests/fixtures/bad.ply');await page.locator('#error-card').waitFor({state:'visible'});await page.click('#dismiss-error');await page.click('#demo');await page.selectOption('#color-mode','height');await page.click('#fit');await page.setViewportSize({width:850,height:640});await page.screenshot({path:'tests/output/compact.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(requests,[]);assert.deepEqual(errors,[]);
 const result={passed:true,checks:['offline startup','WebGL render','mouse rotate with fixed target and radius','D does not override rotation','rotation after wheel','Escape restores rotation','load resets interaction','wheel zoom','right drag pan','view preset','PNG size and bytes','pose unchanged on export','2px interpolation export','ASCII/LE/BE import','invalid PLY recovery','compact layout'],png:dims,errors,requests};await writeFile('tests/output/results.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));
}finally{await browser.close();}
