import{PlyViewer,type ViewName,type ViewerSettings}from'./viewer';import{demoData}from'./demo';import type{PlyData}from'./parse';
declare const __PLY_WORKER__:string;
declare global{interface Window{nativeSavePNG?:(base64:string,name:string)=>Promise<{path?:string;cancelled?:boolean}>}}
const el=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id)as T,select=(id:string)=>el<HTMLSelectElement>(id),input=(id:string)=>el<HTMLInputElement>(id);
let viewer:PlyViewer|undefined,worker:Worker|undefined,generation=0,outputURL='',outputBlob:Blob|undefined,filename='示例场景',toastTimer:ReturnType<typeof setTimeout>,captureBusy=false;
const settings:ViewerSettings={size:2,color:'rgb',mode:'points',background:'#101719',grid:true,axes:true,up:'z'};
function toast(message:string){el('toast').textContent=message;el('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el('toast').hidden=true,4800);}
function showError(message:string){el('error-message').textContent=message;el('error-card').hidden=false;el('status').textContent='操作未完成';}
function setBusy(active:boolean,label='正在读取点云…',cancellable=true){el('busy').hidden=!active;el('busy-label').textContent=label;el('cancel-load').hidden=!cancellable;for(const id of['capture','capture-top'])el<HTMLButtonElement>(id).disabled=active||!viewer?.data;for(const id of['open-top','open-file','demo'])el<HTMLButtonElement>(id).disabled=active&&!cancellable;}
function showData(data:PlyData,name:string,size=0,isDemo=false){
 if(!viewer)return;const format=data.format==='ascii'?'ASCII':data.format.includes('binary')?'二进制':'内置示例';settings.mode=data.triangles?'mesh':'points';settings.color=data.colors?'rgb':'height';viewer.settings={...settings};viewer.setData(data);setInteraction('rotate');filename=name.replace(/\.ply$/i,'');el('file-name').textContent=name;el('breadcrumb').textContent=name;el('scene-name').textContent=filename;el('demo-tag').hidden=!isDemo;el('file-meta').textContent=`${format}${size?' · '+(size/1024/1024).toFixed(1)+' MB':' · 可直接拖入 .ply'}`;el('vertex-count').textContent=data.count.toLocaleString('en-US');el('point-count').textContent=data.count.toLocaleString('en-US');el('face-count').textContent=Math.floor(data.triangles).toLocaleString('en-US');select('render-mode').value=settings.mode;select('color-mode').value=settings.color;for(const o of Array.from(select('render-mode').options))if(o.value!=='points')o.disabled=!data.triangles;select('color-mode').options[0].disabled=!data.colors;select('view-preset').value='iso';el('status').textContent=isDemo?'示例已载入 · 将 PLY 文件拖入视窗即可开始':`已载入 ${name} · 文件在本机处理`;el('error-card').hidden=true;setBusy(false);
}
async function loadFile(file:File){
 if(captureBusy)return;if(!/\.ply$/i.test(file.name)){showError('请选择 .ply 格式的点云或网格文件。');return;}if(file.size>256*1024*1024){showError('此版本支持最大 256 MB 的 PLY 文件，请先降采样或裁剪点云。');return;}if(!viewer){showError('三维渲染器未就绪，请重启程序并检查显卡驱动。');return;}
 generation++;const token=generation;worker?.terminate();setBusy(true);el('error-card').hidden=true;
 try{const buffer=await file.arrayBuffer();if(token!==generation)return;const url=URL.createObjectURL(new Blob([__PLY_WORKER__],{type:'text/javascript'}));worker=new Worker(url);URL.revokeObjectURL(url);worker.onmessage=e=>{if(token!==generation)return;worker?.terminate();worker=undefined;try{if(!e.data.ok)throw Error(e.data.error);showData(e.data.data,file.name,file.size);}catch(error){setBusy(false);showError(error instanceof Error?error.message:'读取失败。');}};worker.onerror=()=>{worker?.terminate();worker=undefined;setBusy(false);showError('点云解析失败或内存不足，请尝试较小的 PLY 文件。');};worker.postMessage(buffer,[buffer]);}catch(error){if(token!==generation)return;setBusy(false);showError(error instanceof Error?error.message:'文件读取失败。');}
}
function cancelLoad(){generation++;worker?.terminate();worker=undefined;setBusy(false);el('status').textContent='已取消读取';}
function applySettings(){viewer?.setSettings({...settings});}
const dialog=el<HTMLDialogElement>('image-dialog');
async function capture(){if(!viewer?.data||captureBusy)return;captureBusy=true;setBusy(true,'正在生成当前视角图片…',false);await new Promise(r=>setTimeout(r,40));try{const result=await viewer.capture(Number(select('resolution').value),Number(select('interpolation').value),input('export-helpers').checked);if(outputURL)URL.revokeObjectURL(outputURL);outputBlob=result.blob;outputURL=URL.createObjectURL(result.blob);el<HTMLImageElement>('output-image').src=outputURL;el('image-info').textContent=`${result.width} × ${result.height} px · PNG · ${(result.blob.size/1024/1024).toFixed(2)} MB`;dialog.showModal();el('status').textContent='图片已生成，可在预览中保存 PNG';}catch(error){showError(error instanceof Error?error.message:'图片生成失败。');}finally{captureBusy=false;setBusy(false);}}
async function saveImage(){
 if(!outputBlob)return;const b=el<HTMLButtonElement>('save-image');b.disabled=true;const safe=filename.replace(/[<>:"/\\|?*\u0000-\u001f]/g,'_').slice(0,100)||'pointcloud',name=`${safe}_${new Date().toISOString().replace(/[:.]/g,'-').slice(0,19)}.png`;
 try{if(window.nativeSavePNG){const base64=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(outputBlob!);});const result=await window.nativeSavePNG(base64,name);if(result.path)toast(`已保存：${result.path}`);}else{const link=document.createElement('a');link.href=outputURL;link.download=name;link.click();toast('PNG 下载已开始');}}catch(error){toast(`保存失败：${error instanceof Error?error.message:String(error)}`);}finally{b.disabled=false;}
}
try{viewer=new PlyViewer(el('viewport'),showError);viewer.onDetail=(shown,total,moving)=>{el('render-detail').textContent=moving?'移动预览 '+shown.toLocaleString('en-US')+' / '+total.toLocaleString('en-US'):'全量显示';};viewer.onPose=p=>{el('camera-values').textContent=`位置  ${p.position.map(v=>v.toFixed(3)).join(', ')}\n目标  ${p.target.map(v=>v.toFixed(3)).join(', ')}\n上向  ${p.up.map(v=>v.toFixed(3)).join(', ')}\n视场角  ${p.fov.toFixed(1)}°`;};showData(demoData(),'室内场景 · 示例',0,true);}catch{showError('无法启动 WebGL 三维渲染。请更新显卡驱动，并确认 Microsoft Edge WebView2 运行时可正常使用。');setBusy(false);}
for(const id of['open-top','open-file'])el(id).onclick=()=>input('file-input').click();input('file-input').onchange=()=>{const f=input('file-input').files?.[0];if(f)void loadFile(f);input('file-input').value='';};el('demo').onclick=()=>{cancelLoad();showData(demoData(),'室内场景 · 示例',0,true);};el('cancel-load').onclick=cancelLoad;el('dismiss-error').onclick=()=>el('error-card').hidden=true;select('view-preset').onchange=()=>viewer?.setView(select('view-preset').value as ViewName);el('fit').onclick=()=>{viewer?.setView('iso');select('view-preset').value='iso';};el('zoom-in').onclick=()=>viewer?.zoom(.8);el('zoom-out').onclick=()=>viewer?.zoom(1.25);
function setInteraction(mode:string){viewer?.setInteraction(mode);for(const other of['rotate','pan']){el(other).classList.toggle('active',other===mode);el(other).setAttribute('aria-pressed',String(other===mode));}el('left-action').textContent=mode==='pan'?'平移（Esc 恢复旋转）':'旋转';}
for(const mode of['rotate','pan'])el(mode).onclick=()=>setInteraction(mode);
window.addEventListener('keydown',e=>{if(e.key==='Escape'&&!dialog.open)setInteraction('rotate');});
input('point-size').oninput=()=>{settings.size=Number(input('point-size').value);el('point-size-value').textContent=`${settings.size.toFixed(1)} px`;applySettings();};select('render-mode').onchange=()=>{settings.mode=select('render-mode').value;applySettings();};select('color-mode').onchange=()=>{settings.color=select('color-mode').value;applySettings();};select('up-axis').onchange=()=>{settings.up=select('up-axis').value;applySettings();select('view-preset').value='iso';};input('show-grid').onchange=()=>{settings.grid=input('show-grid').checked;applySettings();};input('show-axes').onchange=()=>{settings.axes=input('show-axes').checked;applySettings();};
for(const b of document.querySelectorAll<HTMLButtonElement>('.swatch'))b.onclick=()=>{settings.background=b.dataset.color!;applySettings();for(const other of document.querySelectorAll<HTMLButtonElement>('.swatch')){other.classList.toggle('active',other===b);other.setAttribute('aria-pressed',String(other===b));}};
for(const id of['capture','capture-top'])el(id).onclick=capture;el('save-image').onclick=saveImage;el('close-dialog').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog){const b=dialog.getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)dialog.close();}});
let dragDepth=0;document.addEventListener('dragenter',e=>{e.preventDefault();if(e.dataTransfer?.types.includes('Files')&&!captureBusy){dragDepth++;el('drop-overlay').hidden=false;}});document.addEventListener('dragover',e=>{e.preventDefault();if(e.dataTransfer)e.dataTransfer.dropEffect='copy';});document.addEventListener('dragleave',e=>{e.preventDefault();dragDepth=Math.max(0,dragDepth-1);if(!dragDepth)el('drop-overlay').hidden=true;});document.addEventListener('drop',e=>{e.preventDefault();dragDepth=0;el('drop-overlay').hidden=true;const f=e.dataTransfer?.files[0];if(f)void loadFile(f);});window.addEventListener('beforeunload',()=>{worker?.terminate();viewer?.dispose();if(outputURL)URL.revokeObjectURL(outputURL);});
